import {questions,results,mixedReflection,epilogue} from './quiz-data.js';
const QUIZ='/quizzes/anti-therapy/';
const app=document.querySelector('#app');
const letters=['A','B','C'];
const STORAGE='theantitests-therapy-v1';
function valid(s){return s&&['story','answers','tie','result'].includes(s.phase)&&Number.isInteger(s.index)&&s.index>=0&&s.index<=questions.length&&Array.isArray(s.answers)&&s.answers.length<=questions.length&&s.answers.every(a=>letters.includes(a))&&((s.phase==='story'||s.phase==='answers')?(s.index<questions.length&&s.answers.length===s.index):(s.answers.length===questions.length&&s.index===questions.length))&&(s.tie===null||(s.phase==='result'&&leaders(s.answers).includes(s.tie)))&&(s.phase!=='result'||s.tie!==null||leaders(s.answers).length===1);}
let saved=null;try{const candidate=JSON.parse(localStorage.getItem(STORAGE));if(valid(candidate))saved=candidate;}catch{}
function persist(){try{if(state.phase==='intro')localStorage.removeItem(STORAGE);else localStorage.setItem(STORAGE,JSON.stringify(state));}catch{}}

let state={phase:'intro',index:0,answers:[],tie:null};
const escape=(s)=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paragraphs=t=>t.split('\n\n').map(p=>`<p>${escape(p)}</p>`).join('');
export function score(answers){return letters.map(l=>answers.filter(a=>a===l).length);}
export function leaders(answers){const counts=score(answers),max=Math.max(...counts);return letters.filter((l,i)=>counts[i]===max);}
const quizUrl=()=>new URL(QUIZ,location.origin).href;
function saveState(replace=false){const suffix=state.phase==='intro'?'':`#${state.phase==='story'||state.phase==='answers'?`question-${state.index+1}-${state.phase}`:state.phase}`;history[replace?'replaceState':'pushState']({...state,answers:[...state.answers]},'',QUIZ+suffix);}
function change(next,replace=false){state={...state,...next};saveState(replace);persist();render(true);}
function start(){saved=null;change({phase:'story',index:0,answers:[],tie:null});}
function choose(letter){if(state.phase!=='answers'||!letters.includes(letter))throw new Error('Choose A, B or C on an answer screen.');const answers=[...state.answers.slice(0,state.index),letter];const next=state.index+1;change({answers,index:next,phase:next===questions.length?(leaders(answers).length>1?'tie':'result'):'story',tie:null});}
function chooseTie(letter){if(state.phase!=='tie'||!leaders(state.answers).includes(letter))throw new Error('Choose one of the tied options.');change({tie:letter,phase:'result'});}
function winner(){return state.tie||leaders(state.answers)[0];}
function shell(body){const done=state.answers.length;return `<div class="quiz-shell"><aside class="sidebar"><p class="eyebrow">The Anti-Tests / THERAPY CULTURE</p><div class="quiz-identity"><img class="quiz-cover" src="/assets/anti-therapy-self-help-satire-quiz-cover.png" width="872" height="1300" alt="The Great Anti-Therapy Test cover by Simon Star: a person reclining on a blue couch beneath red lettering, illustrating a cynical quiz about self-help and wellness culture."><h2>The Great<br>Anti-Therapy Quiz</h2></div><div class="step-text"><span>${done===15?'All questions answered':'Your progress'}</span><span>${done} / ${questions.length}</span></div><div class="progress" role="progressbar" aria-label="Questions answered" aria-valuemin="0" aria-valuemax="15" aria-valuenow="${done}"><div style="width:${done/15*100}%"></div></div><p class="phase">${state.phase==='story'?'01 Read the scene · 02 Choose':state.phase==='answers'?'01 Read the scene · 02 Choose': 'No right answers. Just yours.'}</p></aside><section class="main-panel" aria-labelledby="screen-title">${body}</section></div>`;}
function render(focus=false){document.title='Anti-Therapy Quiz: Self-Help Satire | The Anti-Tests';let body='';
 if(state.phase==='intro')body=`<span class="number">FREE SELF-HELP CULTURE QUIZ</span><h1 id="screen-title" tabindex="-1">Your inner peace<br>has expired.<br><em>Please upgrade.</em></h1><div class="story"><p>You came looking for a little peace. Apparently that requires a workbook, a retreat and a monthly payment plan.</p><p>This cynical self-help satire quiz explores trauma branding, wellness marketing and the endless pressure to optimize your emotions through 15 sharply familiar scenes. For anyone who suspects their inner child has been added to a mailing list.</p><p>Read each scene, choose A, B or C, and discover your relationship with the emotional improvement marketplace. No breakthrough bundle at the end. We have shown remarkable restraint.</p></div><p class="note">15 questions · 3 main profiles. Allow around 15–20 minutes, depending on your reading pace. Progress is saved in this browser when storage is available. Satire about commercial wellness culture; not therapy, a diagnosis or advice to stop professional care.</p>${saved?`<div class="resume-box"><p>You have a saved ${saved.phase==='result'?'result':'test'} (${saved.answers.length} / ${questions.length} answered).</p><button class="text-button" data-action="resume">${saved.phase==='result'?'View saved result':'Continue your test'}</button></div>`:''}<div class="action-row"><button class="button lime" data-action="start">${saved?'Start a fresh test':'Start the test'} <span aria-hidden="true">↗</span></button></div><p class="note">By Simon Star · Satire, not a psychological assessment.</p>`;
 if(state.phase==='story'){const q=questions[state.index];body=`<span class="number">SCENE ${String(state.index+1).padStart(2,'0')} / 15</span><h1 id="screen-title" tabindex="-1">${escape(q.title)}</h1><div class="story">${paragraphs(q.story)}</div><div class="action-row"><button class="button lime" data-action="show-answers">How do you react? <span aria-hidden="true">→</span></button></div>${state.index>0?'<button class="text-button" data-action="previous">Revisit previous answer</button>':''}`;}
 if(state.phase==='answers'){const q=questions[state.index];body=`<span class="number">QUESTION ${String(state.index+1).padStart(2,'0')} / 15</span><h1 id="screen-title" tabindex="-1">Be honest.<br>Which one is you?</h1><p class="answer-intro">${escape(q.title)}<br>Choose one reaction to continue.</p><div class="answers">${q.answers.map((a,i)=>`<button class="answer" data-answer="${letters[i]}"><span class="letter">${letters[i]}</span><span>${paragraphs(a)}</span></button>`).join('')}</div><button class="text-button" data-action="reread">Read the scene again</button>`;}
 if(state.phase==='tie'){const options=leaders(state.answers);body=`<span class="number">ONE LAST CHOICE</span><h1 id="screen-title" tabindex="-1">A beautifully<br>inconvenient tie.</h1><div class="story"><p>Your ${options.join(' and ')} answers are tied at ${Math.max(...score(state.answers))} each. Choose the thought that feels closest to you right now to settle your result.</p><p>Another healing programme promises to change your life. Which thought feels closest?</p></div><div class="answers">${options.map(l=>`<button class="answer" data-tie="${l}"><span class="letter">${l}</span><span><p>${escape({A:'“I want clear reasoning and honest language before I buy into it.”',B:'“I can see the sales pitch. Part of me still hopes there is something useful.”',C:'“I would rather have room to breathe than another branded transformation.”'}[l])}</p></span></button>`).join('')}</div><p class="note">This decides the tie; your original 15 answers stay as they are.</p>`;}
 if(state.phase==='result'){const l=winner(),r=results[l],counts=score(state.answers);body=`<span class="result-tag">YOUR VERDICT · ${l}</span><h1 id="screen-title" tabindex="-1">${escape(r.title)}</h1><div class="story">${paragraphs(r.text)}</div><div class="score-grid" aria-label="Your answer totals">${letters.map((x,i)=>`<div>${x} answers<strong>${counts[i]}</strong></div>`).join('')}</div>${state.tie?'<p class="note">Your final choice settled a tied score.</p>':''}<details class="result-reflection"><summary>A bit of everything? The Unlabeled Human</summary><div class="story">${paragraphs(mixedReflection)}</div></details><details class="result-reflection"><summary>Epilogue: The Truth About Therapy Culture</summary><div class="story">${paragraphs(epilogue)}</div></details><div class="share-box"><h2>Confess. Then challenge a friend.</h2><p>Share your verdict and invite someone to take the test. The link opens a fresh, unplayed quiz.</p><div class="action-row"><button class="button" data-action="share">Share my result ↗</button><button class="button secondary" data-action="copy">Copy result & link</button></div><div class="status" id="share-status" role="status" aria-live="polite"></div></div><div class="action-row"><button class="button secondary" data-action="start">Take the test again</button><a class="text-button" href="/">All quizzes</a></div><button class="text-button" data-action="edit-last">Change your last answer</button><p class="note">Your humanity is not a subscription tier.<br>From The Great Anti-Series by Simon Star.</p>`;}
 app.innerHTML=shell(body);if(focus){document.querySelector('#screen-title')?.focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});}}
const shareText=()=>`I’m ${results[winner()].title}. Apparently my relationship with self-help has a personality. What’s yours? Take The Great Anti-Therapy Quiz.`;
async function copyResult(){const text=shareText()+'\n'+quizUrl();const status=document.querySelector('#share-status');try{await navigator.clipboard.writeText(text);status.textContent='Copied. Paste it into a message or post.';}catch{status.innerHTML='<label for="share-copy">Select and copy your result below:</label><textarea id="share-copy" class="manual-copy" rows="5" readonly></textarea>';const field=document.querySelector('#share-copy');field.value=text;field.focus();field.select();}}
async function shareResult(){if(navigator.share){try{await navigator.share({title:'The Great Anti-Therapy Quiz',text:shareText(),url:quizUrl()});return;}catch(e){if(e.name==='AbortError')return;}}await copyResult();}
if(app){history.replaceState({...state},'',QUIZ);render();app.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.answer)return choose(b.dataset.answer);if(b.dataset.tie)return chooseTie(b.dataset.tie);switch(b.dataset.action){case'start':start();break;case'resume':if(saved&&valid(saved))change({...saved,answers:[...saved.answers]},true);break;case'show-answers':change({phase:'answers'});break;case'reread':change({phase:'story'});break;case'previous':change({phase:'answers',index:state.index-1,answers:state.answers.slice(0,state.index-1)});break;case'edit-last':change({phase:'answers',index:questions.length-1,answers:state.answers.slice(0,-1),tie:null});break;case'share':void shareResult();break;case'copy':void copyResult();break;}});window.addEventListener('popstate',e=>{if(e.state?.phase==='intro'||valid(e.state)){state={...e.state,answers:[...e.state.answers]};persist();render(true);}});}
