export const questions = [
  {
    "title": "The Child Who Was Never Allowed To Be Average",
    "story": "Average was never a neutral state in your world. It carried consequence. It carried emotional risk. It changed the temperature of the room. You learned this early — not from explicit rules — but from micro facial responses. The subtle tightening around the mouth. The slightly too-slow exhale. The delayed approval that felt like a judgment buffer. You learned that “okay” meant “not enough,” long before you had the language to decode why.\n\nYou remember the report card. The one you were proud of. The one that was objectively good. For sixteen minutes you felt safe in the accomplishment — until someone said you could go beyond that. Not angry, not disappointed, not even sharp — just a soft neutral expectation that this level should now always be achieved. Your system stored this as law. Not excellence — but safety through continuous improvement.\n\nSo you internalized the upgrade loop. You pre-edited harmless words. You rechecked harmless sentences. You perfected harmless tasks no one else even noticed. What felt like discipline to the outside world — was in your world: survival in disguise, because perfection was never ambition, it was protection. As if every “almost perfect” version of you was still endangered.\n\nAs an adult people admire your reliability. They admire your output. They admire your “consistency.” What they cannot see — is that you never learned how to rest inside good enough. You never learned how to relax inside the middle. You only learned to earn your right to exist upward.",
    "answers": [
      "You still believe there is a version of yourself that can permanently secure acceptance — a future final form you must earn before you become truly safe.\n\nYou wait for the day you become that version, even though you have never once reached a finish line that lasted long enough to feel like protection.",
      "You keep striving because absence of improvement activates the threat system. Stillness feels dangerous. Maintaining your level feels dangerous.\n\nAnything below “constantly rising” feels like sliding backward into emotional exposure you once learned to fear.",
      "You logically know perfection is impossible, but your body still behaves as if neutrality leaves you unguarded.\n\nYou perform above average as a reflex — because the memory of average once felt like a place where love could evaporate."
    ]
  },
  {
    "title": "The Apology-After-Every-Sentence Perfectionist",
    "story": "You learned early that asking for help was suspicious terrain. Not because anyone said it directly — but because every request contained a possible emotional penalty. You were the child who apologized before asking a question. Before needing assistance. Before reaching out for clarity. You apologized to soften the risk of being a burden — as if you had to shrink your existence first, to make room for the request itself.\n\nSo your brain built a survival logic: help must be earned. Questions must be pre-softened. Your needs must become small, quiet, and humble before they become allowed. You learned to step toward other people already pre-appeasing. As if your voice had to arrive with a disclaimer: “I’m sorry for taking space. I’m sorry for existing in this moment.”\n\nAs an adult you apologize before opinions. Before corrections. Before your own boundaries. You apologize before starting a sentence and after ending one. Even when there is no harm, no tension, no conflict. It happens automatically — like a reflexive emotional bowing. And when someone tells you that you don’t have to apologize — you instinctively want to apologize for apologizing. Because sorry feels safer than neutral.",
    "answers": [
      "You still shape every interaction through pre-emptive softness — because you believe your needs must be justified before spoken.\n\nYou imagine that reducing your emotional footprint first will prevent disappointment, conflict, or rejection from appearing later.",
      "You apologize to stabilize the emotional climate — because you still believe you are personally responsible for how other people feel.\n\nYou reflexively monitor their reactions more than your own internal signals, as if controlling their mood is the only way to remain safe.",
      "You intellectually know apologies are not necessary this often — yet your body continues to insert them to prevent danger before it exists.\n\nYou are still trying to earn permission to take up space long before you take it."
    ]
  },
  {
    "title": "The Endless Draft Rewriter",
    "story": "You don’t write drafts. You write pre-drafts. Then you write drafts. Then you write revisions of drafts that technically never even existed in a completed form. You perfect the invisible layers beneath the visible layer. The version that will never be seen — becomes the most important one. You try to predict what the final version should become, before the final version even exists. The standard keeps rising faster than you can meet it.\n\nYou try to commit — but as soon as something becomes “almost done” your brain instantly upgrades the metric again. Almost-done becomes not-yet-good-enough. Not-yet-good-enough becomes rewrite. Rewrite becomes rewrite-of-rewrite. You are chasing a target that moves upward with every improvement you make. You cannot finish — because finishing feels like freezing your value at a specific level. And that feels dangerous.\n\nAs an adult your life is full of drafts that are 90% complete — but emotionally impossible to finish. Ending something means risking final measurement. Endless improvement feels safer than final evaluation. You polish potential, because potential feels more “protected” than outcome.",
    "answers": [
      "You rewrite because you believe the perfect draft is always one more iteration away — and you cannot walk away while there’s still a theoretical improvement available.\n\nYou assume completion is failure, because completion exposes you to possibility of final judgment.",
      "You rewrite because elevating the standard feels automatic — each revision immediately reveals a new reason to revise again.\n\nYou believe the work must keep evolving to stay safe — because static results feel vulnerable and fragile.",
      "You rewrite because potential feels safer than result — potential cannot be proven wrong, but a finished version can be.\n\nYou avoid finalization because finalization could confirm you were never as exceptional as you hoped you might become."
    ]
  },
  {
    "title": "The Hyper-Corrector of Microscopically Small Mistakes",
    "story": "You learned to scan reality at a microscopic level. Your nervous system became a surveillance mechanism — not for danger in the world, but for tiny imperfections in your own output. The smallest typo, the smallest mispronunciation, the smallest aesthetic asymmetry… it all triggers the same internal urgency as a real threat would for someone else. You don’t correct because you enjoy precision. You correct because you fear the emotional meaning that could attach to an imperfection.\n\nMicroscopic mistakes feel like they could reveal something deeper — that there is something fundamentally flawed beneath the surface that small errors might expose. So you track everything at pixel resolution. Every detail becomes load bearing. You feel responsible not only for avoiding mistakes — but for proving that you never produce them by accident. The smallest slip feels like evidence. Evidence that could invalidate all previous excellence — instantly.\n\nAs an adult this becomes invisible labor. Most people don’t even see the micro-corrections you make in real-time — yet these corrections cost you emotional bandwidth every single hour. You are editing the world silently as you move through it — and you cannot rest while there is still one detail that might betray you.",
    "answers": [
      "You correct to maintain the illusion that you are incapable of small flaws — because one small flaw could become symbolic of a much bigger defect.\n\nYou cannot tolerate the idea that imperfection might be interpreted as essence — not momentary oversight.",
      "You correct because the body believes that tiny errors accumulate into vulnerability — and your nervous system registers small mistakes as precursors to danger.\n\nYou treat micro-correction as emotional insurance — paying premiums constantly, to prevent collapse later.",
      "You correct because the meaning assigned to small errors still feels dangerously heavy — and the stakes attached to tiny imperfections still feel non-negotiable.\n\nYou would rather invest hours in micro-precision than risk the exposure of being seen as merely ordinary."
    ]
  },
  {
    "title": "The “If I Feel Calm, Something Is Wrong” Person",
    "story": "Your system does not trust calm. Calm feels suspicious. Calm feels like the quiet hallway before impact. The waiting room before the bad news arrives. You were conditioned to brace — to anticipate — to pre-scan for threats before they had any chance to appear. Calm was never comfort. Calm was a warning signal that something unseen was forming just outside of perception.\n\nSo you learned to self-activate tension when the world didn’t provide it. If external chaos faded, your body generated internal vigilance to replace it. Stillness felt emotionally unrealistic. Rest felt like losing control. You believed — unconsciously — that peace was a temporary illusion, and that preparing yourself for disruption was the responsible way to survive.\n\nAs an adult you often cannot identify what is wrong — but the body insists something is. And because perfection was the way to avoid danger, now even neutral states feel unsafe — because the absence of threat feels like the wrong data input. You preemptively brace for a collapse that has not yet happened.",
    "answers": [
      "You maintain tension because the absence of stress feels like the system is malfunctioning — and your nervous system believes fear is the baseline reality.\n\nYou assume peace is fraudulent — because the world you learned in taught you that calm precedes disruption.",
      "You generate micro-anxiety to create emotional stability — because certainty feels more accessible through controlled tension than through unpredictable calm.\n\nYou internalize vigilance as safety — because safety through relaxation feels unreliable.",
      "You cannot relax because relaxation still activates danger detection — and neutral states feel like emotional ambush territory.\n\nYou prepare for disaster even when disaster has not been scheduled."
    ]
  },
  {
    "title": "The Achievement-Proof Self-Worth Seeker",
    "story": "You accomplished things that objectively mattered. You crossed thresholds that other people would have celebrated. You hit milestones that should have altered your internal map of who you believed you were. Yet none of it changed anything inside. Every achievement evaporated on contact. Every success was immediately disqualified. You could not store it. You could not internalize it. You could not metabolize it as proof of value.\n\nYou learned early that achievement was not the *source* of worth — achievement was the *condition* required to avoid punishment, rejection, or threat. So every new accomplishment became temporary insurance. It didn’t make you safe — it merely bought you time. Worth was never gained — it was only temporarily not lost.\n\nAs an adult, this creates a strange existential math. No matter what you achieve — the numerator grows, but the denominator expands with it, making every result feel suddenly insufficient again. You keep raising your own bar faster than you could ever reach it. Which means you are endlessly chasing worth, while endlessly invalidating the evidence that you already have it.",
    "answers": [
      "You continue collecting achievements because you believe the next one will finally “count” — and you cannot stop searching for the version of success that finally changes how you feel.\n\nYou hope that one future result will become the breakthrough proof that finally sticks inside you permanently.",
      "You escalate your goals because each win feels small the moment you reach it — your nervous system upgrades the standard instantly, making victory feel irrelevant.\n\nYou don’t celebrate progress — because your body believes celebration would be premature and dangerous.",
      "You discard achievements before they can matter — because if you never allow yourself to feel successful, you never have to risk losing the feeling later.\n\nYou protect yourself from disappointment by refusing to internalize success before it can be taken away."
    ]
  },
  {
    "title": "The Invisible Scorekeeper of Social Expectations",
    "story": "You track social expectations in the background the same way others track weather: constantly, silently, automatically. You observe what people value, what people react to, what people subtly reward, and you calibrate yourself in real time. Not to manipulate — but to avoid misalignment. You internalized very early that being out of sync could result in disapproval, disappointment, or subtle withdrawal of connection.\n\nSo you became a precision instrument for social readjustment. While others speak freely — you observe the entire emotional landscape and micro-correct in advance. You feel the tension before it arrives. You compensate before anything becomes off balance. You shape yourself into the version of you that feels the least likely to produce discord.\n\nAs an adult this becomes nearly invisible labor. People feel “comfortable” around you because you are doing the emotional work before they ever notice anything is happening. Which is why this kind of perfectionism is socially rewarded — yet internally exhausting. You do not get credit for the work because no one sees you doing it — not even yourself.",
    "answers": [
      "You match expectations because social harmony feels like the only safe baseline — and you would rather adapt than risk creating disappointment.\n\nControlling the emotional climate around you feels easier than trusting that you are allowed to remain authentic within it.",
      "You track what people want because you still believe approval must be earned through perfect attunement to others.\n\nYou maintain relational safety through constant micro-adjustment — as if misalignment could collapse the entire connection.",
      "You never let yourself relax into your own preferences — because you fear your authentic alignment will conflict with someone’s unspoken standard.\n\nYou maintain internal flexibility as a survival skill — while never fully arriving as yourself."
    ]
  },
  {
    "title": "The Avoider Who Doesn’t Start Because They Might Fail",
    "story": "People assume perfectionists are always executing, always performing, always producing output. They do not understand that sometimes the perfectionistic mind becomes so catastrophically overloaded — that it becomes safer not to begin at all. Avoidance becomes the safest optimization path. If you never start, you cannot fail. If you never reveal the attempt, no one can measure it. And if there is no measurable performance — then nothing can collapse.\n\nYour resistance isn’t laziness. It’s pre-emptive self-protection. The beginning feels like a trap door — one that could drop you straight into the humiliation you’ve spent a lifetime trying to avoid. So your brain convinces you that waiting is safer. Planning is safer. Preparing is safer. Delaying is safer. Thinking about doing the thing becomes more tolerable than actually doing the thing — because potential is invulnerable, but execution can shatter.\n\nAs an adult, the outside world sees procrastination. What they do not see is the internal negotiation: the cost-benefit analysis of emotional threat. Movement toward action feels like walking into exposure unshielded. You don’t avoid because you don’t care — you avoid because you care so much that the possibility of failure feels catastrophic at a structural level.",
    "answers": [
      "You delay action because you still believe your value is at risk the moment you commit — and avoiding the beginning feels safer than risking the ending.\n\nYou protect your identity by refusing to test it against reality.",
      "You avoid because every small task feels like it carries enormous symbolic potential — and one imperfect action could “prove” your worst fear about yourself.\n\nYou would rather remain theoretical excellence than risk becoming measured mediocrity.",
      "You resist starting because your body still believes silence is safer than evidence — and potential keeps you protected behind a wall of what might still be possible.\n\nYou fear the moment a result becomes real more than you desire the result itself."
    ]
  },
  {
    "title": "The Self-Editor of Emotions",
    "story": "You learned that emotions were not meant to be expressed freely — they were meant to be filtered, refined, moderated, or made more aesthetically acceptable before release. You didn’t learn emotional literacy — you learned emotional management. Not because anyone asked you to lie — but because authenticity felt too dangerous to reveal raw. You were taught that you must first perfect the emotional version of yourself before anyone else could see it.\n\nSo you became your own internal censor. You redact intensity before anyone hears it. You adjust tone to avoid activating threat. You soften content before it ever leaves your mouth. You correct the emotional data so it becomes socially “clean.” You learned that “being real” is not allowed to happen unedited — because unedited could threaten connection. You live behind revised versions of your truth — believing your inner world must become coherent before anyone can witness it.\n\nAs an adult this becomes chronic emotional translation. You are constantly converting how you actually feel into something more manageable, more tolerable, more strategically safe. You perform emotional precision more than emotional honesty — because vulnerability feels like exposure that cannot be reversed.",
    "answers": [
      "You edit feelings because you still believe your raw emotional reality might be judged as childish, dramatic, or unstable.\n\nYou protect yourself from rejection by pre-filtering before it ever touches the outside world.",
      "You modulate emotions because you fear the impact they could have — and you believe it is your responsibility to keep relational equilibrium intact.\n\nYou self-regulate on behalf of other people — because you never learned that regulating for yourself was enough.",
      "You compress your inner world into the smallest possible format — because you assume your full emotional bandwidth would exceed what others can tolerate.\n\nYou’d rather hide your depth than risk being misunderstood at full size."
    ]
  },
  {
    "title": "The Validation Chaser Who Outsources Their Value",
    "story": "Your self-worth became something that lived outside of you — something stored in other people’s reactions, tone, micro-expressions, feedback, approval. You were trained to use external signals to determine internal truth. If they approved you, you were safe. If they didn’t — you were not just wrong, you were existentially unstable. You became someone who checks reflections instead of the mirror — because internal calibration never felt reliable enough to stand on its own.\n\nSo you learned to hunt for signals. Subtle approval, subtle praise, subtle reassurance. You wait for confirmation that you are “right.” You wait for someone else to declare the meaning of your effort. The opinion of others does not just influence your self-concept — it *creates* it. Without external validation, your accomplishments feel weightless. Without a witness, your value feels unconfirmed.\n\nAs an adult this becomes a loop with no exit. You constantly search outside yourself for evidence you are allowed to exist at this level. You outsource your self-worth to other people’s interpretations — and in the process, disconnect from your internal authority. You evaluate your value based on the way the world reacts — not the way you actually feel.",
    "answers": [
      "You chase validation because you still believe your worth is something that needs to be granted by others — and cannot be generated internally.\n\nYou depend on external recognition not as compliment, but as emotional permission to continue existing at your current level.",
      "You seek external proof because you believe other people’s judgments are more accurate than your own — and outsourcing feels safer than trusting your internal voice.\n\nYou stabilize yourself through their reactions, because autonomy still feels structurally unsafe.",
      "You constantly look outward because your nervous system still believes self-worth is stored out there — not in here.\n\nYou scan for signals before you experience your own internal truth — because you never learned how to hold value without witnesses."
    ]
  },
  {
    "title": "The Collector of Certification, Courses, and “Just One More Skill”",
    "story": "You keep adding new skills, new courses, new certificates, new systems — not because you actually lack capability, but because capability never feels internally established. You treat knowledge as an infinite staircase — one that you must keep climbing before you are allowed to act, choose, produce, or claim authority. Competence becomes a provisional status — something that expires quickly without constant renewal.\n\nYou don’t pursue education for expansion — you pursue education for self-permission. Each new skill temporarily defers the fear that you are still “not enough” at your current level. You tell yourself: “Once I know this next thing — then I can finally begin.” But after each new thing, another new thing appears. The list is bottomless. You cannot reach the top because the top is a moving theoretical construct.\n\nAs an adult you have more knowledge than many people who actually execute. Yet you feel permanently prequalified instead of qualified. You spend life accumulating preparation instead of arriving in ownership.",
    "answers": [
      "You keep learning because you still believe success requires complete readiness — and you cannot risk making visible moves while you have not learned everything yet.\n\nYou postpone action until the last missing piece is acquired — even though the missing piece keeps reproducing.",
      "You continue collecting skills because you believe future competence will protect you from humiliation — and more knowledge feels like a safety fortress.\n\nYou build expertise not to express yourself — but to defend against anticipated judgment.",
      "You accumulate courses because you believe identity must be built externally, brick by brick — credential by credential — until you can justify your right to exist at the level you secretly already occupy.\n\nYou restrict personal evolution by believing knowledge must come first — not self-trust."
    ]
  },
  {
    "title": "The One Who Thinks Love Must Be Earned Through Performance",
    "story": "You learned that love was conditional — not freely given, not natural, not inherent to existence — but something that needed to be earned through results. Love was not a baseline. Love was a reward. And rewards were not guaranteed. Affection arrived more reliably when you excelled — not when you existed. You internalized the concept that love had criteria — a performance metric — a threshold you had to maintain.\n\nSo your nervous system built a core rule: you are only safe when you impress. If you relax, you are replaceable. If you underperform, you are unworthy. You became someone who tries to become lovable rather than someone who feels loved. You learned to present excellence before identity — because identity alone never felt sufficient. You learned to become valuable first — human second.\n\nAs an adult this creates emotional asymmetry. You give more than you receive. You serve more than you express. You outperform in relationships because you fear that if you stop performing — people will forget why you were worth keeping. You confuse being chosen with being useful. You confuse being appreciated with being needed. You confuse attachment with dependency.",
    "answers": [
      "You still believe your worth must be proven through output — and you try to earn love by becoming someone whose value is undeniable.\n\nYou maintain performance because identity alone feels too fragile to trust.",
      "You adapt yourself around other people’s preferences — because meeting their ideal version of you feels safer than risking them meeting the real one.\n\nYou secure connection by becoming what they need — not what you are.",
      "You fear that if you show the unpolished version of yourself, love will evaporate — so you keep presenting the refined version to avoid the pain of losing what you never truly felt secure in.\n\nYou accept love as conditional because unconditional love still feels structurally unbelievable."
    ]
  },
  {
    "title": "The Ritualistic Perfect Routine Engineer",
    "story": "You learned that routines were not simply habits — they were stabilizers. Rituals were not optional — they were protective infrastructure. Structure was safety. Predictability was safety. Precision was safety. The routine became the scaffolding that kept you from collapsing internally. You were not optimizing efficiency. You were engineering emotional containment.\n\nChildhood taught you that chaos was unpredictable and unpredictable meant danger. So you built routines that felt like controlled worlds — miniature systems where nothing unexpected could enter without permission. Every repeated sequence, every standardized method, every controlled pre-step, every identical resetting of the environment… became a private architecture of emotional security.\n\nAs an adult, routine becomes ritual. Repetition becomes regulation. You do things the same way not because it is practical — but because it is emotionally stabilizing. Systems stop feeling optional and start feeling necessary. The ritual becomes the spell you use to prevent things from spiraling. The routine is the firewall against internal collapse.",
    "answers": [
      "You cling to the same precise sequence because predictability feels like emotional armor — and changing the order feels like removing protection you worked endlessly to construct.\n\nYou maintain ritual not as efficiency — but as survival engineering.",
      "You optimize routines because you believe perfection must occur at the environmental level first — before any action inside that environment is allowed to begin.\n\nYou create controlled preconditions because internal chaos feels easier to manage when the external world is flawlessly arranged.",
      "You refine routines endlessly because repetition becomes a refuge — a place where nothing can surprise you, where nothing can slip through the cracks, where everything stays inside the known limits.\n\nYou use ritual the way others use reassurance — to keep the world from destabilizing your nervous system."
    ]
  },
  {
    "title": "The Silent Self-Punisher",
    "story": "You learned to punish yourself quietly. Not through visible explosions, not through dramatic breakdowns — but through subtle internal penalties. You became your own judge, jury, and executioner long before you ever had the self-awareness to understand why. Self-punishment became the invisible tax you paid for not meeting the impossible standard you never agreed to — but still inherited.\n\nYou did not learn how to repair after mistakes. You learned how to reduce yourself after mistakes. You learned to withdraw warmth from yourself. You learned to shrink, restrict, tighten, and emotionally starve yourself just enough to “balance the ledger.” You believed that pain was required to restore order. That punishment was required to maintain safety. That harm was the price of imperfection.\n\nAs an adult, you punish yourself without even labeling it as punishment. You withhold rest. You sabotage joy. You deny softness. You build mental sentences that never end. Silence becomes the discipline. Self-neglect becomes the enforcement. And the world sees “high standards” — when in reality, what you are practicing is quiet internal retribution.",
    "answers": [
      "You punish yourself because you believe consequences must be paid — and you fear what would happen if you ever allowed yourself to move forward cleanly after mistakes.\n\nYou enforce pain on yourself because you fear leniency would collapse the structure holding you together.",
      "You punish yourself through subtle deprivation — denying relief, denying compassion, denying care — because comfort feels undeserved unless perfection has been achieved first.\n\nYou believe kindness is a privilege that must be earned, not a right you inherently possess.",
      "You punish yourself because internal harm feels safer than external harm — and you learned long ago that hurting yourself first prevents the world from hurting you later.\n\nYou preemptively inflict emotional damage because anticipation feels less terrifying than surprise."
    ]
  },
  {
    "title": "The One Who Believes Their Value Is Conditional on Results",
    "story": "You absorbed the belief that your value is not located inside you — but in the outcome you produce. You learned that what you are is inseparable from what you accomplish. Your identity became performance. Your worth became metrics. Your self-concept became the scoreboard of output — constantly updated, constantly recalculated, constantly at risk of downgrade.\n\nThis belief did not arrive from nowhere. It was inherited through subtle reinforcement — praise when you exceeded, neutrality when you were average, disappointment when you fell short. You learned that your existence was not inherently meaningful — it was conditionally valid. You were not taught to *be* — you were taught to *perform being*.\n\nAs an adult this belief becomes an entire worldview: results are the currency that determines whether you are allowed to belong, to connect, to take up space. Internal value never feels stable — it must always be proven externally. And because results expire instantly, the pressure to re-prove value never ends. You are perpetually “up for renewal.”",
    "answers": [
      "You believe your worth must constantly be validated through visible outcomes — because you fear that if you stop producing, your value will vanish.\n\nYou do not trust the version of you that exists without an active achievement attached to your name.",
      "You attach identity to results because identity without results feels empty — and the emptiness feels unbearable, like standing in a void without reference points.\n\nYou cling to performance because you cannot anchor your worth in yourself.",
      "You continue to evaluate your value through results — because you still fear that internal worth is unstable, unreliable, and unprovable.\n\nYou treat worth like documentation — something that must be continually updated, verified, and reissued."
    ]
  }
];
export const results = {
  "A": {
    "title": "The Future-Based Safety Strategist",
    "text": "Your answers lean towards the book’s future-focused profile: the hope that one more improvement will finally make you feel ready, accepted or beyond criticism. The finished version of you is apparently due next quarter. It has been due next quarter for some time.\n\nYou may recognise the moving finish line: another revision, another skill, another achievement before you let yourself arrive. The effort can be thoughtful and capable, but being permanently under construction leaves very little room to enjoy what is already here.\n\nThis is a reflection on your choices, not proof of why you developed these habits. You do not need to become flawless to deserve consideration. An ordinary finished draft is allowed to exist. So are you."
  },
  "B": {
    "title": "The Emotional Climate Regulator",
    "text": "Your answers lean towards the book’s profile of monitoring, adjusting and trying to keep things steady. You notice reactions, anticipate expectations and may edit yourself before anyone has actually requested a revision. Somewhere, an imaginary control room has been operating without a lunch break.\n\nBeing considerate matters. The exhausting part is treating every mood, standard and possible disappointment as your personal maintenance assignment. You may find it easier to keep adjusting than to leave a little uncertainty unresolved.\n\nThis label describes a pattern in your answers, not your nervous system or childhood. Your preferences belong in the room too. You can care about other people without accepting a permanent position as their emotional weather service."
  },
  "C": {
    "title": "The Self-Protective Worth Preserver",
    "text": "Your answers lean towards the book’s guarded profile: keeping possibilities open, limiting exposure and recognising a standard as impossible while still feeling reluctant to step outside it. Your inner critic has apparently made “just in case” a full-time occupation.\n\nYou may recognise the relief of a project that cannot be judged because it is not quite finished, or a feeling that stays private because explaining it seems risky. Caution can protect your time and privacy. It can also keep things you care about permanently waiting in the wings.\n\nThis is a reflective label, not a diagnosis or an account of your past. A result cannot measure your worth. You are allowed to be seen as an ordinary person with unfinished thoughts, rather than a flawless product awaiting certification."
  }
};
export const mixedReflection = "More Than One Pattern\n\nYou can chase the next improvement, manage the mood and hide the unfinished draft in the same afternoon. Mixed answers do not mean you have failed to be a consistent perfectionist. Please do not revise them for presentation purposes.\n\nThe three profiles come from the book’s interpretation framework. They overlap and are not validated psychological scales. Read what feels useful, leave what does not fit, and remember that a quiz cannot establish the cause of your habits.";
export const epilogue = "Good Enough Does Not Need a Reference Letter\n\nThe book uses protection and acceptance as a lens for exploring perfectionism. That lens may resonate with you; it does not establish what happened in your childhood, how your nervous system works or why you feel as you do.\n\nYou can notice the apologies, revisions and shifting standards without turning recognition into another improvement project. Even self-reflection is allowed to finish before it becomes a performance review.\n\nYour value is not the number of things you finish, polish or prevent from going wrong. You can close this page without submitting a better version of yourself.";