export const questions = [
  {
    "title": "The Parent Who Still Tries To Be “The Perfect Example”",
    "story": "You work hard to show your children what “good” looks like. Not just in behavior — but in tone, reaction, patience, and emotional quality. You try to model calm even when you feel chaos. You try to model confidence even when you secretly doubt yourself. You try to model stability even when your body is tired, overloaded, or quietly overwhelmed. You are not pretending — you are trying to protect your children from the fear you once had.\n\nYou learned long ago that being average was risky, and now you carry that pressure into parenting. You want to show them safety — but safety became tangled with flawlessness. You don’t just want your children to grow up feeling safe… you want them to grow up seeing a version of you that is safe. You don’t want them to see the parts of you that are unsure, or scared, or messy, or human — because you still believe that might teach them the wrong lesson about themselves. You think that if they see vulnerability — it will turn into weakness. You believe stability must be performed, not lived.\n\nAs an adult parent, this becomes complicated emotional geometry. You try to give them the freedom you never had — while still holding yourself to standards you cannot comfortably live inside. You are trying to break perfectionism for them — while still carrying perfectionism inside yourself. You want them to know softness and self-worth and acceptance — but you fear they will learn fear from watching you struggle. So instead of letting them see your humanity, you try to curate the safest version of you possible. You try to be their proof that “safe” exists.",
    "answers": [
      "You try to be perfect because you believe your children need a flawless model — and you fear that seeing your mistakes will teach them weakness.\n\nYou protect them by hiding the parts of you that were never allowed to exist openly.",
      "You keep performing emotional strength because you believe they will trust the world more if they see a parent who never loses control.\n\nYou read your children’s safety through your performance — not your truth.",
      "You push yourself to be “better” because you still believe children deserve a version of you that doesn’t struggle — even if you privately collapse later.\n\nYou want to end the cycle for them — but you are still stuck inside it yourself."
    ]
  },
  {
    "title": "The Parent Who Apologizes Constantly (Even When Nothing Is Wrong)",
    "story": "You say “sorry” before anything has gone wrong. You apologize when you need a moment. You apologize when you speak up. You apologize when you take space. You apologize before you even ask a question. You do not do this because you want to — you do it because your nervous system still believes that being a burden is dangerous. You are afraid that even normal needs might create disappointment. So “sorry” became the cushion between you and potential rejection.\n\nAs a parent this reflex gets stronger. You apologize before saying no. You apologize before setting a boundary. You apologize when you are tired, short-tempered, or emotionally unavailable — even if those moments were normal human moments. You apologize because you fear your natural imperfection might harm them. You fear that small mistakes might make them feel unsafe — the way you once felt unsafe.\n\nYour children do not see you as a burden. They simply see you as a parent. But your nervous system learned that safety must be earned through softness first. And now you are still trying to remove threat from the environment before it ever exists — even inside the home that is yours.",
    "answers": [
      "You apologize constantly because you still believe every emotional disruption must be softened — and you fear that being direct might damage their trust.\n\nYou think that shrinking yourself keeps the peace.",
      "You apologize because you take emotional responsibility for everyone’s comfort — and you fear your reactions will be too much for others to handle.\n\nYou try to manage their feelings before you even allow your own.",
      "You apologize because you believe asking for understanding or space could be misinterpreted — and apologizing feels like safer preparation than asking for what you need.\n\nYou give up your comfort to protect their emotional state first."
    ]
  },
  {
    "title": "The Parent Who Rewrites Every Message Before Sending It",
    "story": "You don’t just write a message — you pre-edit the emotional landing of the message. You rewrite texts to teachers, other parents, family members, school groups, coaches, doctors, playdate invitations, birthday replies… You spend more time making sure the message cannot be misunderstood than writing what you actually feel. You polish neutral sentences like you are trying to avoid secret traps that could explode later.\n\nYou want to avoid sounding demanding. You want to avoid sounding careless. You want to avoid sounding defensive. You want to avoid sounding uninterested. You are constantly correcting to prevent misinterpretation. You are not afraid of the text itself — you are afraid of the possible emotional meaning others might attach to it.\n\nAs an adult parent this becomes a hidden full-time emotional editor job. You rewrite for clarity, then you rewrite for softness, then you rewrite for social acceptability, then you rewrite again because maybe it wasn’t gentle enough. You are not writing a text. You are designing emotional risk prevention. You believe that the more you control the wording — the more you control the future outcome.",
    "answers": [
      "You rewrite because you believe language must be perfectly safe — and any small misphrasing could create unnecessary conflict.\n\nYou try to remove all possible danger before anything can be taken the wrong way.",
      "You rewrite because you still think your value is tied to how others interpret you — and you cannot risk being misunderstood.\n\nYou control communication because communication becomes evidence of who you are.",
      "You rewrite because keeping messages “protected” feels easier than trusting that normal language will be enough.\n\nYou defend your worth by ensuring nothing you say can be criticized."
    ]
  },
  {
    "title": "The Parent Who Fixates On Tiny Mistakes",
    "story": "You notice every small slip you make with your children — even when they don’t notice at all. A slightly sharp tone. A moment of impatience. A mis-timed reaction. A rushed answer. A comment you wish you phrased kinder. You replay these tiny moments long after everyone else has moved on. You treat them like proof that you are failing in ways nobody sees but you.\n\nYou track micro errors the way other people track major events. The small things feel like signals of something dangerous underneath. You fear that one tiny mistake could shape their self-esteem, their trust in you, or their emotional future. You believe that small errors are not harmless — they are potential patterns waiting to form.\n\nAs an adult parent, this becomes a heavy emotional load. You do not allow small mistakes to simply be mistakes. You turn them into moral data. You believe every imperfection means something about your character — not just your behavior in a moment. You fear that one small lapse could make you accidentally repeat what once hurt you. So you try to prevent every tiny crack before it grows.",
    "answers": [
      "You fixate on tiny mistakes because you fear they might become memories that mark your children the way small things once marked you.\n\nYou try to over-correct because you think perfection prevents emotional damage.",
      "You fixate because you believe that protecting them requires absolute emotional precision — and any misstep feels like a potential wound.\n\nYou treat tiny corrections as a necessary part of responsible parenting.",
      "You fixate because you believe your value as a parent can collapse from the smallest evidence of imperfection.\n\nYou fear that one moment out of alignment could rewrite how they see you forever."
    ]
  },
  {
    "title": "The Parent Who Panics When Things Feel Calm",
    "story": "When the house is peaceful, when the kids are settled, when nothing is chaotic… your nervous system doesn’t always relax. Instead, it starts scanning. Calm does not automatically register as safety. Calm sometimes feels like the warning before the storm. Calm feels like the suspicious silence just before something breaks. You do not rest — you prepare.\n\nYou learned early that emotional danger could appear suddenly. Not scheduled. Not predictable. Not announced. So your body developed a system: it is better to brace first, than get caught unprepared later. Calm became the place where fear has time to form. Calm became the moment where threat might be hiding, not gone.\n\nAs an adult parent this creates tension even on the good days. You finally get a quiet moment — and you immediately start thinking something must be wrong, or that something is about to go wrong, or that you missed something you should have done. The nervous system believes calm is unrealistic. It believes stress is the baseline. So when peace appears — your body starts searching for the hidden danger it still expects.",
    "answers": [
      "You panic during calm because stillness feels unsafe — and your nervous system thinks protection requires constant readiness.\n\nYou react to calm like it is a trap, not a neutral moment.",
      "You panic during calm because preparing for the worst feels safer than hoping for the best.\n\nYou use fear as a shield because hope once felt dangerous.",
      "You panic during calm because peace feels temporary — and you are trying to rehearse survival before threat returns.\n\nYou cannot enjoy calm — because calm activates the part of you that still waits for impact."
    ]
  },
  {
    "title": "The Parent Who Can’t Feel Proud — No Matter What They Achieve",
    "story": "You have done so much as a parent — and yet it rarely lands inside you as real success. You show up. You care deeply. You work hard. You keep trying again even when you are exhausted. Other people tell you that you are doing well. Sometimes your children even say it directly. But the feeling of pride does not stay. It slides off you before it has time to sink in.\n\nYou learned that achievement was not safety — it was only temporary permission to continue. Every accomplishment expired fast. Every milestone needed to be raised again. So now when you do something meaningful or beautiful or genuinely good for your children, it does not create a sense of internal “I did it.” Instead, it becomes a small confirmation that you must now maintain or exceed that level forever. Pride feels like a luxury you have not earned the right to keep.\n\nAs an adult parent this makes progress feel invisible. You do not get to enjoy what you build. You move from task to task like none of it matters until the next level is reached. You do not celebrate — you reset. You do not anchor success — you replace it with pressure to deliver the next proof. Your body still believes that pausing to feel proud will make you vulnerable again.",
    "answers": [
      "You cannot feel proud because the moment you succeed, you instantly assume you must now do better — and you fear slowing down might collapse everything you built.\n\nYou protect yourself by never landing fully on accomplishment.",
      "You cannot feel proud because each win becomes too small too fast — and your brain upgrades the standard faster than your heart can catch up.\n\nYou never stop long enough to feel what you have already achieved.",
      "You cannot feel proud because internal worth never felt stable — and success cannot stay if worth cannot stay.\n\nYou do not absorb achievement because you don’t believe you are allowed to keep it."
    ]
  },
  {
    "title": "The Parent Who Always Tracks What Others Expect",
    "story": "You are constantly aware of what other adults might think about how you parent. You scan teachers, family, other parents, partners, social norms, online opinions, school standards, cultural expectations, parenting “rules,” expert advice… and you absorb all of it quietly. Not because you want to impress anyone — but because you fear being judged as careless, irresponsible, or not “good enough.”\n\nYou track expectations the way some people track weather. You predict emotional temperature before it arrives. You try to prevent embarrassment, conflict, misunderstanding, or criticism — before it can even happen. You are not just trying to protect your own image. You are trying to protect your children from social consequences they never asked for. You believe you must keep everything aligned so they never get hurt because of you.\n\nAs an adult parent, this makes you feel like you are always “on.” Even at home. Even when no one is watching. You perform safety. You pre-adjust behavior. You adapt your tone, your decisions, your responses — not based on what feels right for you and your child — but based on what you fear others would judge. You never fully stand inside your own authority. You act through predicted reaction.",
    "answers": [
      "You track expectations because you believe social alignment protects your children — and you fear that being misjudged might harm them socially or emotionally.\n\nYou choose safety through conformity.",
      "You track expectations because you still outsource internal permission to other people’s opinions — and you trust their standards more than your own.\n\nYou evaluate parenting through imagined external evaluation.",
      "You track expectations because you don’t want your imperfection to become a public flaw — and you fear one wrong move will define you.\n\nYou protect your identity by never letting anyone see a version of you that isn’t perfectly controlled."
    ]
  },
  {
    "title": "The Parent Who Avoids Starting Because They Might Mess It Up",
    "story": "You want to try new things as a parent — new approaches, new routines, new learning moments, new types of connection — but sometimes you freeze before the beginning. You delay starting projects, habits, or parenting changes because the fear of doing it wrong feels heavier than the hope of doing it right. You do not fear failure in theory — you fear failure in front of your children.\n\nYou imagine the disappointment. You imagine the misunderstanding. You imagine the emotional fallout. You imagine the moment where the effort falls apart and becomes proof that you were not capable. So your brain chooses delay as protection. Planning feels safer than beginning. Research feels safer than action. Pausing feels safer than committing. You would rather wait until you are fully ready — even if “fully ready” never arrives.\n\nAs an adult parent this becomes a hidden blocker. You are not lazy. You are not unmotivated. You care so much that execution feels dangerous. You try to prevent disappointment before it can exist. You try to protect your children from seeing your imperfection by avoiding starting things you might not be able to finish perfectly.",
    "answers": [
      "You avoid starting because you believe mistakes could impact who they become — and you cannot risk shaping them wrong.\n\nYou protect them by controlling the possibility of imperfect outcomes.",
      "You avoid starting because you believe the emotional cost of trying and failing is bigger than the cost of not trying at all.\n\nYou choose safety through non-action rather than risk through action.",
      "You avoid starting because you still believe your ability must be proven first — before you are allowed to begin.\n\nYou hold yourself in preparation mode, waiting for permission that will never come."
    ]
  },
  {
    "title": "The Parent Who Edits Their Emotions Before Speaking",
    "story": "You do not speak your feelings in real-time. You translate them. You soften them. You turn them into something smoother, cleaner, safer — before your children ever hear them. You want to protect their emotional world, so you censor your inner world. You believe raw emotion might overwhelm them, scare them, or mark them in ways you cannot repair later.\n\nYou learned that feelings should be carefully managed before they are expressed. So even now as a parent, you remove the edges from your truth before it leaves your mouth. You filter frustration. You dilute sadness. You reduce disappointment. You treat your own internal emotional reality like something that must be transformed into a digestible form — even when it costs you authenticity and connection.\n\nAs an adult parent, this becomes emotional distance inside your own home. You want to be real — but you fear reality might be too much. You do not want your children to experience the emotional weight you once lived inside. So you try to protect them from your inner world — by hiding your inner world.",
    "answers": [
      "You edit feelings because you still believe your raw emotion will harm your children — and you fear they cannot handle the intensity.\n\nYou protect them by turning everything into a softer version of truth.",
      "You edit feelings because you were taught emotions must be controlled, not shared — and now you treat emotional expression like a responsibility, not a need.\n\nYou believe your feelings must be perfected before they are spoken.",
      "You edit feelings because being emotionally honest feels riskier than being emotionally filtered — and you trust control more than transparency.\n\nYou hide vulnerability because you fear visibility more than silence."
    ]
  },
  {
    "title": "The Parent Who Needs Validation To Feel Like A “Good Parent”",
    "story": "You collect signals from outside yourself to decide if you are doing this right. A comment from a teacher, a compliment from another parent, a good report from school, a friendly smile from a pediatrician, a small moment of approval from family — these moments feel like evidence that you are safe as a parent. Without external confirmation, you do not feel solid inside your role.\n\nYour nervous system was trained to rely on outside reactions to know if you were acceptable. So now you measure your value through the expressions and responses of others. You don’t ask: “How do I feel about how I am parenting?” You ask: “How does this look from the outside?” The world’s reaction becomes the mirror you judge yourself through — even at home.\n\nAs an adult parent this creates a dependency loop. You can do everything right — and still feel uncertain if nobody notices. You can give energy, patience, time, tenderness — and still question your value if no one reflects it back. The validation you are looking for is support — but your nervous system interprets it as permission to exist correctly.",
    "answers": [
      "You rely on validation because the outside world still feels like the judge — and you want confirmation that you are not failing your children.\n\nYou trust feedback more than self-trust.",
      "You rely on validation because you believe other people see what you cannot see — and you feel safer following their interpretation.\n\nYou outsource your worth to external reaction.",
      "You rely on validation because you never learned how to internally recognize your own effort — and praise feels like oxygen you cannot generate yourself.\n\nYou wait for someone else to make your goodness real."
    ]
  },
  {
    "title": "The Parent Who Keeps Taking More Courses Before Feeling “Ready”",
    "story": "You keep learning. Parenting books, online programs, YouTube explanations, webinars, child development threads, nervous system workshops, attachment theory videos, trauma informed parenting podcasts, gentle discipline guides, Montessori reels, ADHD tip lists, self regulation modules… You are always learning something new. Not because you lack information — but because you never feel fully allowed to act on what you already know.\n\nYou believe there is still one more missing piece you must find first. One more concept. One more tool. One more method. One more insight. Each new resource feels like the step that might finally make you “qualified.” You are not addicted to information — you are afraid of not having enough certainty to prevent harm.\n\nAs an adult parent, this turns parenting into endless preparation mode. You postpone trying new approaches because you think knowing more will make the emotional cost smaller if something goes wrong later. You believe learning protects your children. You believe study equals safety. You believe if you understand everything perfectly — then you will not repeat the things that hurt you.",
    "answers": [
      "You keep learning because you believe competence must be absolute before taking action — and you fear making a mistake without the perfect knowledge behind you.\n\nYou treat learning as prevention.",
      "You keep learning because every time you understand one topic — you see three more topics you now feel responsible to master.\n\nYou believe parenting requires full education before full participation.",
      "You keep learning because potential feels safer than implementation — and the idea of perfect preparation protects you from the fear of real world outcomes.\n\nYou feel safer in preparation than in experience."
    ]
  },
  {
    "title": "The Parent Who Believes Love Must Be Earned (For Them And Their Kids)",
    "story": "You grew up learning that love was not freely given — it was something you had to qualify for. You had to perform well, behave well, achieve well, impress well… before love felt stable. So now as a parent, part of you still fears that if you are not doing everything right, you do not deserve connection. You try to “earn” your own place inside your own home.\n\nAnd sometimes — without meaning to — you are afraid your children might also need to earn it too. Not because you want them to. Not because you believe children should. But because your nervous system still carries the belief that love must be justified, not simply received. You try to love freely — yet you feel pressure to make sure you are doing “enough” today to deserve the safety of their closeness.\n\nAs an adult parent this creates tension between what you believe and what your body still remembers. You want them to feel unconditional love. You want them to know they never have to perform for worth. But the part of you that was trained to prove value still tries to show up as perfect first — before allowing softness. You are trying to give them what you didn’t have — but the old rules still sit inside your wiring.",
    "answers": [
      "You believe love must be earned because you fear that unconditional love is fragile — and you think protecting it requires constant proof.\n\nYou perform safety instead of trusting that safety already exists.",
      "You believe love must be earned because you think effort is the currency of belonging — and you fear that without effort, connection may disappear.\n\nYou work harder at being lovable than allowing yourself to simply be loved.",
      "You believe love must be earned because you still cannot trust that feeling loved without doing anything is allowed.\n\nYou want your children to grow up differently — but you are still trying to unlearn this rule yourself."
    ]
  },
  {
    "title": "The Parent Who Builds Perfect Routines To Stay Safe",
    "story": "You do not build routines just to stay organized. You build routines so life doesn’t suddenly shift in ways you cannot predict. Predictability feels like emotional protection. Structure feels like safety. If things are done the same way, in the same order, with the same rhythm — you can breathe easier. Your routines are not just habits. They are your safety architecture.\n\nYou learned that chaos was not just uncomfortable — chaos was threat. So now you try to create a world where your children will not have to feel that same unstable fear. You create morning rituals, bedtime sequences, school preparation flows, calm-down steps, transition anchors… not because you want control in a strict or rigid way — but because ritual makes the world feel steered, not random.\n\nAs an adult parent this becomes one of the hardest perfectionism patterns to see — because it looks practically helpful from the outside. And sometimes it genuinely is. But internally, you are constantly micro-managing the environment so nothing unexpected can break through the surface. The routine becomes the shield that prevents the old danger from returning — even if the danger is no longer here.",
    "answers": [
      "You engineer perfect routines because predictability feels like protection — and you cannot relax while randomness is still possible.\n\nYou try to remove threat by removing surprise.",
      "You engineer perfect routines because you believe emotional safety must happen at the environment level first — before internal safety can exist.\n\nYou build structure so connection can seem controllable.",
      "You engineer perfect routines because you believe consistency prevents collapse — and collapse once felt unbearable.\n\nYou keep perfect rhythm to avoid feeling unguarded."
    ]
  },
  {
    "title": "The Parent Who Punishes Themselves Quietly",
    "story": "You don’t explode. You don’t collapse loudly. You don’t scream into rooms. You punish yourself silently. You punish yourself through tension, withdrawal, coldness toward yourself, guilt spirals, and private emotional consequences no one can see. You believe you must “pay internally” for anything you think you should have done better as a parent.\n\nYou do not accept mistake + repair. You do mistake + punishment. You turn small moments into internal sentencing. Not because you want to be dramatic — but because you believe pain is the cost of not being perfect. You think suffering resets the balance. You learned long ago that when you failed, warmth was removed — so now you remove warmth from yourself.\n\nAs an adult parent, this becomes invisible emotional debt-collecting. You deny yourself rest. You deny yourself comfort. You deny yourself kindness. You deny yourself the right to just be human. You think you cannot afford compassion because compassion feels like “permission to fail again.” So you stay tense instead of healed.",
    "answers": [
      "You punish yourself because you believe consequence is required — and without internal punishment, you fear imperfection will repeat.\n\nYou choose pain to prevent risk.",
      "You punish yourself because you feel you must earn forgiveness — and without self-punishment, forgiveness feels undeserved.\n\nYou treat harm as the entry cost to grace.",
      "You punish yourself because hurting yourself first feels safer than waiting for the world to hurt you.\n\nYou attack yourself before anyone else gets the chance."
    ]
  },
  {
    "title": "The Parent Who Thinks Their Value Depends on Results",
    "story": "You measure your worth as a parent through outcomes. Through how well your child behaves. Through how confidently they speak. Through how they perform at school. Through how they handle emotions. Through how other adults describe them. Through how “good” they appear on the outside. You treat your child’s visible results as a reflection of your identity — not as their separate journey.\n\nYou learned that worth was something earned through achievement — not something held from within. So now when your child struggles, you panic inside. Not because you judge them harshly — but because it feels like it proves something dark about you. You do not see their growth as theirs — you see it as the measurable scoreboard of how safe you are allowed to feel as a parent.\n\nAs an adult parent this becomes unfair pressure on both sides. You cannot let them be messy. And you cannot let yourself be ordinary. You try to protect them from your old story by forcing a new one — but perfectionism still whispers that value must be maintained through performance. You want them to feel inherently worthy. You just don’t know how to give them something you never received.",
    "answers": [
      "You attach your value to results because you believe parenting success must be measurable — and results prove that you are not failing.\n\nYou fear what it means if there is nothing visible to measure.",
      "You attach your value to results because you fear their struggles reflect your flaws — and the world might interpret their difficulty as your incompetence.\n\nYou take their journey personally because you were never allowed to have your own.",
      "You attach your value to results because you still believe worth is conditional — and internal value feels too unstable to trust.\n\nYou evaluate yourself the way others once evaluated you."
    ]
  }
];
export const results = {
  "A": {
    "title": "The Future Protector Parent",
    "text": "Your perfectionism is fueled by fear of future harm, future loss, future regret, future “damage.” You try to prevent everything before it could ever happen — because the future once felt dangerous and unpredictable.\n\nYou protect your children by trying to remove every risk before it exists — even emotional risk.\n\nGentle reminder:\nYour kids don’t need a future where nothing goes wrong.\nThey need a future where recovery is possible, even when things do."
  },
  "B": {
    "title": "The Emotional Climate Stabilizer Parent",
    "text": "You try to keep things emotionally smooth, balanced, stable… because you once learned chaos had consequences. You shape yourself constantly around others to protect safety in the room.\n\nThis is not weakness. This is what you had to learn.\n\nGentle reminder:\nYour children do not need you to control the climate.  \nThey need to see that storms can pass — without losing connection."
  },
  "C": {
    "title": "The Worth-Protecting Parent",
    "text": "You protect your value — not because you are vain — but because your nervous system still believes worth can disappear if something goes wrong.\n\nSo you guard yourself through perfection before opening softness.\n\nGentle reminder:\nYour children do not need a perfect parent to feel safe.\nThey need a parent who knows they are worthy even when they struggle."
  }
};
export const intro = "Perfectionism inside parenting is quiet. It shows up in small moments — in the pressure to be a “good example,” in the fear of doing things wrong, in the constant monitoring of how we appear to others. We try to be calm, patient, stable, and endlessly capable… while still carrying old beliefs from when we were children ourselves.\n\nThis book is not here to blame you or judge you. Parenting is already heavy enough.\n\nThis book is here to help you see where perfectionism still lives inside you — and how those survival patterns can now soften. Not by becoming perfect parents… but by becoming kinder to yourself while parenting.";
export const reflection = "Perfectionism in parenting was never about being impressive.\nIt was about being safe.\n\nYour nervous system tried to protect your children by trying to protect you — at the same time.\n\nYou learned impossible standards because you once needed them to survive.\nAnd now you are trying to raise children in a world where survival shouldn’t require self-erasure.\n\nThis book is not asking you to become less responsible, less intentional, or less careful.\nIt is asking you to become more gentle with the part of you that is still trying so hard to earn safety.\n\nYou are not teaching your children perfection.\nYou are teaching them how to exist.\n\nAnd the most healing gift they can receive…\nis witnessing a parent who can stay human — and still be enough.";
